version: '3'

services:
  s3:
    container_name: minio
    image: quay.io/minio/minio
    restart: on-failure
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - /mnt/data:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-admin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
